Add support for using the XTest extension in wxUIActionSimulator
Fixes wxUIActionSimulator under wxGTK3, see #17530.

(cherry picked from commit a4716916b7d53adff5648311f6f400b533b460f8)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -961,6 +961,8 @@ HILDON2_LIBS
 HILDON2_CFLAGS
 HILDON_LIBS
 HILDON_CFLAGS
+XTST_LIBS
+XTST_CFLAGS
 LIBNOTIFY_LIBS
 LIBNOTIFY_CFLAGS
 GNOMEVFS_LIBS
@@ -1109,6 +1111,7 @@ with_gnomevfs
 with_libnotify
 with_hildon
 with_opengl
+with_xtest
 with_dmalloc
 with_sdl
 with_regex
@@ -1414,6 +1417,8 @@ HILDON_CFLAGS
 HILDON_LIBS
 HILDON2_CFLAGS
 HILDON2_LIBS
+XTST_CFLAGS
+XTST_LIBS
 WEBKIT_CFLAGS
 WEBKIT_LIBS
 CAIRO_CFLAGS
@@ -2336,6 +2341,7 @@ Optional Packages:
   --with-libnotify        use libnotify for notifications
   --with-hildon           use Hildon framework for Nokia 770/800/810
   --with-opengl           use OpenGL (or Mesa)
+  --with-xtest            use XTest extension
   --with-dmalloc          use dmalloc library (http://dmalloc.com/)
   --with-sdl              use SDL for audio on Unix
   --with-regex            enable support for wxRegEx class
@@ -2414,6 +2420,8 @@ Some influential environment variables:
               C compiler flags for HILDON2, overriding pkg-config
   HILDON2_LIBS
               linker flags for HILDON2, overriding pkg-config
+  XTST_CFLAGS C compiler flags for XTST, overriding pkg-config
+  XTST_LIBS   linker flags for XTST, overriding pkg-config
   WEBKIT_CFLAGS
               C compiler flags for WEBKIT, overriding pkg-config
   WEBKIT_LIBS linker flags for WEBKIT, overriding pkg-config
@@ -5337,6 +5345,35 @@ fi
 
           { $as_echo "$as_me:${as_lineno-$LINENO}: result: $result" >&5
 $as_echo "$result" >&6; }
+
+
+          withstring=
+          defaultval=$wxUSE_ALL_FEATURES
+          if test -z "$defaultval"; then
+              if test x"$withstring" = xwithout; then
+                  defaultval=yes
+              else
+                  defaultval=no
+              fi
+          fi
+
+# Check whether --with-xtest was given.
+if test "${with_xtest+set}" = set; then :
+  withval=$with_xtest;
+                        if test "$withval" = yes; then
+                          wx_cv_use_xtest='wxUSE_XTEST=yes'
+                        else
+                          wx_cv_use_xtest='wxUSE_XTEST=no'
+                        fi
+
+else
+
+                        wx_cv_use_xtest='wxUSE_XTEST=${'DEFAULT_wxUSE_XTEST":-$defaultval}"
+
+fi
+
+
+          eval "$wx_cv_use_xtest"
 
 
 fi
@@ -35946,6 +35983,93 @@ if test "$wxUSE_UIACTIONSIMULATOR" = "yes" ; then
     $as_echo "#define wxUSE_UIACTIONSIMULATOR 1" >>confdefs.h
 
     SAMPLES_SUBDIRS="$SAMPLES_SUBDIRS uiaction"
+    if test "$wxUSE_XTEST" = "yes" ; then
+
+pkg_failed=no
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for XTST" >&5
+$as_echo_n "checking for XTST... " >&6; }
+
+if test -n "$PKG_CONFIG"; then
+    if test -n "$XTST_CFLAGS"; then
+        pkg_cv_XTST_CFLAGS="$XTST_CFLAGS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"xtst\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "xtst") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_XTST_CFLAGS=`$PKG_CONFIG --cflags "xtst" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+if test -n "$PKG_CONFIG"; then
+    if test -n "$XTST_LIBS"; then
+        pkg_cv_XTST_LIBS="$XTST_LIBS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"xtst\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "xtst") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_XTST_LIBS=`$PKG_CONFIG --libs "xtst" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        XTST_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "xtst"`
+        else
+	        XTST_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xtst"`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$XTST_PKG_ERRORS" >&5
+
+
+                { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: XTest extension not found" >&5
+$as_echo "$as_me: WARNING: XTest extension not found" >&2;}
+                wxUSE_XTEST="no"
+
+
+elif test $pkg_failed = untried; then
+
+                { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: XTest extension not found" >&5
+$as_echo "$as_me: WARNING: XTest extension not found" >&2;}
+                wxUSE_XTEST="no"
+
+
+else
+	XTST_CFLAGS=$pkg_cv_XTST_CFLAGS
+	XTST_LIBS=$pkg_cv_XTST_LIBS
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+
+                GUI_TK_LIBRARY="$GUI_TK_LIBRARY $XTST_LIBS"
+                CFLAGS="$XTST_CFLAGS $CFLAGS"
+                CXXFLAGS="$XTST_CFLAGS $CXXFLAGS"
+                $as_echo "#define wxUSE_XTEST 1" >>confdefs.h
+
+
+fi
+    fi
 fi
 
 if test "$wxUSE_DC_TRANSFORM_MATRIX" = "yes" ; then
